export const mobile = '/assets/mobile.png'
export const backend = '/assets/backend.png'
export const creator = '/assets/creator.png'
export const web = '/assets/web.png'
export const carrent = '/assets/carrent.png'
export const jobit = '/assets/jobit.png'
export const tripguide = '/assets/tripguide.png'
export const damaiLogo = '/assets/damai_logo.png'
export const American = '/assets/American.png'
export const Japan = '/assets/Japan.webp'
export const Taiwan = '/assets/Taiwan.jpeg'

export const desktop_pc = './desktop_pc/scene.gltf'
export const planet = './planet/scene.gltf'

export const appIcon = './favicon.ico'
export const appLogo = './logo.svg'
